require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/service_provisions", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # ServiceProvision. As you add validations to ServiceProvision, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      ServiceProvision.create! valid_attributes
      get service_provisions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      service_provision = ServiceProvision.create! valid_attributes
      get service_provision_url(service_provision)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_service_provision_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      service_provision = ServiceProvision.create! valid_attributes
      get edit_service_provision_url(service_provision)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new ServiceProvision" do
        expect {
          post service_provisions_url, params: { service_provision: valid_attributes }
        }.to change(ServiceProvision, :count).by(1)
      end

      it "redirects to the created service_provision" do
        post service_provisions_url, params: { service_provision: valid_attributes }
        expect(response).to redirect_to(service_provision_url(ServiceProvision.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new ServiceProvision" do
        expect {
          post service_provisions_url, params: { service_provision: invalid_attributes }
        }.to change(ServiceProvision, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post service_provisions_url, params: { service_provision: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested service_provision" do
        service_provision = ServiceProvision.create! valid_attributes
        patch service_provision_url(service_provision), params: { service_provision: new_attributes }
        service_provision.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the service_provision" do
        service_provision = ServiceProvision.create! valid_attributes
        patch service_provision_url(service_provision), params: { service_provision: new_attributes }
        service_provision.reload
        expect(response).to redirect_to(service_provision_url(service_provision))
      end
    end

    context "with invalid parameters" do
    
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        service_provision = ServiceProvision.create! valid_attributes
        patch service_provision_url(service_provision), params: { service_provision: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested service_provision" do
      service_provision = ServiceProvision.create! valid_attributes
      expect {
        delete service_provision_url(service_provision)
      }.to change(ServiceProvision, :count).by(-1)
    end

    it "redirects to the service_provisions list" do
      service_provision = ServiceProvision.create! valid_attributes
      delete service_provision_url(service_provision)
      expect(response).to redirect_to(service_provisions_url)
    end
  end
end
